schema_version: 1

context:
  name: loro
  version: "1.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/loro-${{ version }}.tar.gz
  sha256: f543b85c77f7366df2162de1c00e3dd2c2c75171b7e9670cffc0b6ac561d7293

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.8,<2.0
    - pip
    - rust
  run:
    - python

tests:
  - python:
      imports:
        - loro
      pip_check: true

about:
  summary: Python bindings for [Loro](https://loro.dev)
  homepage: https://loro.dev
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - AH-Merii
    - Leeeon233
