schema_version: 1

context:
  name: loro
  version: "1.8.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/loro-${{ version }}.tar.gz
  sha256: d22dc17cbec652ed8bf627f801a0a32e27a87b4476a2ab96f45a02d163d733ae

build:
  number: 1
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.8,<2.0
    - cargo-bundle-licenses
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
  host:
    - python
    - maturin >=1.8,<2.0
    - pip
    - rust
  run:
    - python

tests:
  - python:
      imports:
        - loro
      pip_check: true

about:
  summary: Python bindings for [Loro](https://loro.dev)
  homepage: https://loro.dev
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - AH-Merii
    - Leeeon233
